# Generated by Django 5.1 on 2024-09-03 14:30

import django.db.models.deletion
import gestaoo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteImobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[gestaoo.models.validar_cpf])),
                ('comissao', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[gestaoo.models.validar_cpf])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[gestaoo.models.validar_cpf])),
                ('data_aquisicao', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dono', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestaoo.donoimovel')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('propriedade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestaoo.propriedade')),
                ('tamanho', models.FloatField()),
            ],
            bases=('gestaoo.propriedade',),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.imovel')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.imovel'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.imovel')),
            ],
        ),
    ]
