# Generated by Django 5.1 on 2024-09-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoo', '0002_agenteimobiliario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteimobiliario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='agenteimobiliario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='donoimovel',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='donoimovel',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='status',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.cliente'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.imovel'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.imovel'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.imovel'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.contrato'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.cliente'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoo.imovel'),
        ),
    ]
